terraform {
  backend "azurerm" {
    resource_group_name  = "websock"                   # Your TF_STATE_RESOURCE_GROUP_NAME
    storage_account_name = "tfstateewr0flal"           # The unique storage account name generated by the script
    container_name       = "tfstate-container"         # The container name you set
    key                  = "terraform.tfstate"
  }
}
